package cn.zxg.dao;

import cn.zxg.pojo.Zxg;
import cn.zxg.pojo.ZxgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZxgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZXG
     *
     * @mbggenerated
     */
    int countByExample(ZxgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZXG
     *
     * @mbggenerated
     */
    int deleteByExample(ZxgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZXG
     *
     * @mbggenerated
     */
    int insert(Zxg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZXG
     *
     * @mbggenerated
     */
    int insertSelective(Zxg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZXG
     *
     * @mbggenerated
     */
    List<Zxg> selectByExample(ZxgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZXG
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Zxg record, @Param("example") ZxgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZXG
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Zxg record, @Param("example") ZxgExample example);
}