package cn.zxg.pojo;

public class Zxg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZXG.A
     *
     * @mbggenerated
     */
    private String a;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZXG.A
     *
     * @return the value of ZXG.A
     *
     * @mbggenerated
     */
    public String getA() {
        return a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZXG.A
     *
     * @param a the value for ZXG.A
     *
     * @mbggenerated
     */
    public void setA(String a) {
        this.a = a == null ? null : a.trim();
    }
}